export DATABASE_USER_NAME=root
export DATABASE_PASSWORD=
export DATABASE_HOST=127.0.0.1
export DATABASE_PORT=3306
export DATABASE_SCHEMA=cart
export DATABASE_CHARSET=utf8mb4
export DATABASE_PARSE_TIME=True
export DATABASE_LOC=Local

export AUTH_TOKEN_SIGNING_KEY=4h0pp1ngk4r7
export AUTH_TOKEN_EXPIRATION_SECONDS=7200

export SERVER_PORT=:8080